# Generated by Django 2.2.12 on 2021-10-27 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_auto_20211017_2140'),
    ]

    operations = [
        migrations.CreateModel(
            name='cos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cos_status', models.CharField(max_length=4, verbose_name='雲端訂單')),
            ],
            options={
                'verbose_name': '雲端訂單',
                'verbose_name_plural': '雲端訂單',
                'db_table': 'cos_status',
            },
        ),
        migrations.CreateModel(
            name='Lan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lan_status', models.CharField(max_length=4, verbose_name='網路檢測')),
            ],
            options={
                'verbose_name': '網路檢測',
                'verbose_name_plural': '網路檢測',
                'db_table': 'lan_status',
            },
        ),
    ]
