# Generated by Django 2.2.12 on 2021-10-27 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0003_cos_lan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cos',
            old_name='cos_status',
            new_name='cos_db',
        ),
        migrations.AlterModelTable(
            name='cos',
            table='cos_db',
        ),
    ]
